from engine.constants.settings import env_float

ENV_SETTLEMENT_TIMEOUT = "SETTLEMENT_TIMEOUT"
ENV_SETTLEMENT_POLL_INTERVAL = "SETTLEMENT_POLL_INTERVAL"

DEFAULT_SETTLEMENT_TIMEOUT = 30.0
DEFAULT_SETTLEMENT_POLL_INTERVAL = 1.5

SETTLEMENT_TIMEOUT: float = env_float(ENV_SETTLEMENT_TIMEOUT, DEFAULT_SETTLEMENT_TIMEOUT)
SETTLEMENT_POLL_INTERVAL: float = env_float(
    ENV_SETTLEMENT_POLL_INTERVAL,
    DEFAULT_SETTLEMENT_POLL_INTERVAL,
)
